### ISSUE TITLE
es module?

### ISSUE THREAD

**Issue by tsukimizake** [y047aka/emaki#5]
es moduleとcommonjsについてあまりよくわかっていないのだけれど、nodeで実行するcliでは基本的にcommonjsを使う一方で現状のコードはesmoduleになっているっぽい？

typescript化しようとしていて何かはまっています　(と思ったがはまっているのはshebang周りであって関係なかった)

**Comment by pxfnc** [comment]
あたらしめのnode.jsはesmoduleを直接実行できるので、むしろ最近は基本的にesmoduleの形式でどうしてもかけない場合にcommonjsを使うようなイメージがあります(出典がなくてすみません:pray:)

**Comment by tsukimizake** [comment]
全然知らなかったぜ
